### ISSUE TITLE
DYFI Review: Update README

### ISSUE THREAD

**Issue by mhearne-usgs** [vinceq-usgs/dyfi4#10]
- The README is written as if it were still on gitlab, and displays the url of an internal gitlab server
 - Refers to a setup_env.sh which does not exist.
 - Refers to an env_vars.sh which does not exist.
 - References to miniconda venvs are unnecessarily confusing.  I think you could say something like:

1. Install anaconda or miniconda from (anaconda/miniconda url)
2. Create a virtual environment by typing "conda create -n dyfi python=3.5"
3. Activate this environment by typing "source activate dyfi"
4. Type `pip install -r requirements.txt`
5. Type `pip install pytest-cov`
6. Type `pip install -e .`

**Comment by vinceq-usgs** [comment]
I changed the installation procedure so that you should be able to install fresh from ./install.sh alone. Let me know how this works for you.

**Comment by vinceq-usgs** [comment]
Fixed
