### ISSUE TITLE
DYFI Review: Tests fail

### ISSUE THREAD

**Issue by mhearne-usgs** [vinceq-usgs/dyfi4#11]
I tried running the tests a couple of different ways (Makefile points to a file that doesn't exist.)

A file is attached showing the results of the tests.
[dyfi_errors.txt](https://github.com/vinceq-usgs/dyfi4/files/1691088/dyfi_errors.txt)

**Comment by vinceq-usgs** [comment]
I put phantomjs in the requirements list. Try installing again and see if it works now.

**Comment by vinceq-usgs** [comment]
Fixed
