### ISSUE TITLE
DYFI Review: Cannot see documentation

### ISSUE THREAD

**Issue by mhearne-usgs** [vinceq-usgs/dyfi4#12]
As noted in another issue, the documentation links in the README point to a USGS internal server.  Is there a place where I can see the documentation.  I'm particularly curious about the documentation for functions in the code - I don't recognize the format you're using to document the code, but it doesn't look like it is consistently applied (many classes/methods are not documented), and I can't tell if it captures input arguments.

ShakeMap (as an example) uses the Google style, which can be seen on this page:
https://usgs.github.io/shakemap/manual4_0/tg_contributing.html (scroll down to "Example").

**Comment by vinceq-usgs** [comment]
I'm using Sphinx autodoc for the in-file documentation. However, I uploaded the documents to https://vinceq-usgs.github.io/dyfi/ and it's not working right--- it seems like it can't get to .css files in other directories. I will need to figure this out, but in the meantime, you can get the documentation by running the 'makedoc' script I put in the repo's root directory.

**Comment by vinceq-usgs** [comment]
Okay I figured out how to do this automatically. The manual is now visible at:
https://vinceq-usgs.github.io/dyfi4/
